---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice ### name of the microservice
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice # pod name
    spec:
      serviceAccountName: default
      containers:
      - name: service # conatiner name
        image: gcr.io/google-samples/microservices-demo/cartservice
        ports:
        - containerPort: 7070
        env:
        - name: PORT
          value: "7070"
        - name: REDIS_ADDR
          value: "redis-cart:6379"
          
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice # name Service of microservice 
spec:
  type: ClusterIP
  selector:
    app: cartservice # name of the microservice
  ports:
  - protocol: TCP
    port: 7070
    targetPort: 7070