---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice ### name of the microservice
spec:
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice # pod name
    spec:
      serviceAccountName: default
      containers:
      - name: service # conatiner name
        image: gcr.io/google-samples/microservices-demo/emailservice:v0.5.2
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice # name Service of microservice 
spec:
  type: ClusterIP
  selector:
    app: emailservice # name of the microservice
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8080