---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice ### name of the microservice
spec:
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice # pod name
    spec:
      serviceAccountName: default
      containers:
      - name: service # conatiner name
        image: gcr.io/google-samples/microservices-demo/paymentservice
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
          
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice # name Service of microservice 
spec:
  type: ClusterIP
  selector:
    app: paymentservice # name of the microservice
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051