---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice ### name of the microservice
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice # pod name
    spec:
      serviceAccountName: default
      containers:
      - name: service # conatiner name
        image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.5.2
        ports:
        - containerPort: 3550
        env:
        - name: PORT
          value: "3550"
          
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice # name Service of microservice 
spec:
  type: ClusterIP
  selector:
    app: productcatalogservice # name of the microservice
  ports:
  - protocol: TCP
    port: 3550
    targetPort: 3550